apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: leisure0213/webapp:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: webapp-config
