name: CloudCal CI/CD

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r webApp/requirements.txt

    - name: Run basic test script
      run: |
        python webApp/test.py

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cloudcal:webapp-${{ github.sha }} ./webApp

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/cloudcal:webapp-${{ github.sha }}

    - name: (Optional) Tag as latest on main branch
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/cloudcal:webapp-${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/cloudcal:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/cloudcal:latest
